export default [
	{ name: 'Germany', code: 'DE' },
	{ name: 'Afghanistan', code: 'AF' },
	{ name: 'Albania', code: 'AL' },
	{ name: 'Algeria', code: 'DZ' },
	{ name: 'Andorra', code: 'AD' },
	{ name: 'Angola', code: 'AO' },
	{ name: 'Antigua and Barbuda', code: 'AG' },
	{ name: 'Argentina', code: 'AR' },
	{ name: 'Armenia', code: 'AM' },
	{ name: 'Azerbaijan', code: 'AZ' },
	{ name: 'Australia', code: 'AU' },
	{ name: 'Australia - Canberra', code: 'AU_CA' },
	{ name: 'Australia - Sydney', code: 'AU_SY' },
	{ name: 'Austria', code: 'AT' },
	{ name: 'Bahrain', code: 'BH' },
	{ name: 'Bangladesh', code: 'BD' },
	{ name: 'Barbados', code: 'BB' },
	{ name: 'Belarus', code: 'BY' },
	{ name: 'Belgium', code: 'BE' },
	{ name: 'Benin', code: 'BJ' },
	{ name: 'Bolivia', code: 'BO' },
	{ name: 'Bosnia and Herzegovina', code: 'BA' },
	{ name: 'Botswana', code: 'BW' },
	{ name: 'Brazil', code: 'BR' },
	{ name: 'Brazil - Brasilia', code: 'BR_BR' },
	{ name: 'Brazil - Rio de Janeiro', code: 'BR_RI' },
	{ name: 'Brazil - Sao Paulo', code: 'BR_SP' },
	{ name: 'Brunei', code: 'BN' },
	{ name: 'Bulgaria', code: 'BG' },
	{ name: 'Burkina Faso', code: 'BF' },
	{ name: 'Burundi', code: 'BI' },
	{ name: 'Cabo Verde', code: 'CV' },
	{ name: 'Cambodia', code: 'KH' },
	{ name: 'Cameroon', code: 'CM' },
	{ name: 'Canada', code: 'CA' },
	{ name: 'Canada - Ottawa', code: 'CA_OT' },
	{ name: 'Canada - Toronto', code: 'CA_TO' },
	{ name: 'Canada - Vancouver', code: 'CA_VA' },
	{ name: 'Central African Republic', code: 'CF' },
	{ name: 'Chad', code: 'TD' },
	{ name: 'Chile', code: 'CL' },
	{ name: 'China', code: 'CN' },
	{ name: 'China - Chengdu', code: 'CN_CH' },
	{ name: 'China - Hongkong', code: 'CN_HK' },
	{ name: 'China - Kanton', code: 'CN_KN' },
	{ name: 'China - Peking', code: 'CN_PK' },
	{ name: 'China - Shanghai', code: 'CN_SH' },
	{ name: 'Colombia', code: 'CO' },
	{ name: 'Congo', code: 'CG' },
	{ name: 'Congo, Democratic Republic', code: 'CD' },
	{ name: 'Costa Rica', code: 'CR' },
	{ name: 'Côte d\'Ivoire', code: 'CI' },
	{ name: 'Croatia', code: 'HR' },
	{ name: 'Cuba', code: 'CU' },
	{ name: 'Cyprus', code: 'CY' },
	{ name: 'Czech Republic', code: 'CZ' },
	{ name: 'Denmark', code: 'DK' },
	{ name: 'Djibouti', code: 'DJ' },
	{ name: 'Dominica', code: 'DM' },
	{ name: 'Dominican Republic', code: 'DO' },
	{ name: 'Ecuador', code: 'EC' },
	{ name: 'Egypt', code: 'EG' },
	{ name: 'El Salvador', code: 'SV' },
	{ name: 'Equatorial Guinea', code: 'GQ' },
	{ name: 'Eritrea', code: 'ER' },
	{ name: 'Estonia', code: 'EE' },
	{ name: 'Ethiopia', code: 'ET' },
	{ name: 'Fiji', code: 'FJ' },
	{ name: 'Finland', code: 'FI' },
	{ name: 'France', code: 'FR' },
	{ name: 'France - Lyon', code: 'FR_LY' },
	{ name: 'France - Marseille', code: 'FR_MA' },
	{ name: 'France - Paris', code: 'FR_PA' },
	{ name: 'France - Strasbourg', code: 'FR_ST' },
	{ name: 'Gabon', code: 'GA' },
	{ name: 'Gambia', code: 'GM' },
	{ name: 'Georgia', code: 'GE' },
	{ name: 'Ghana', code: 'GH' },
	{ name: 'Greece', code: 'GR' },
	{ name: 'Greece - Athens', code: 'GR_AT' },
	{ name: 'Grenada', code: 'GD' },
	{ name: 'Guatemala', code: 'GT' },
	{ name: 'Guinea', code: 'GN' },
	{ name: 'Guinea-Bissau', code: 'GW' },
	{ name: 'Guyana', code: 'GY' },
	{ name: 'Haiti', code: 'HT' },
	{ name: 'Honduras', code: 'HN' },
	{ name: 'Hungary', code: 'HU' },
	{ name: 'India', code: 'IN' },
	{ name: 'India - Bangalore', code: 'IN_BA' },
	{ name: 'India - Chennai', code: 'IN_CH' },
	{ name: 'India - Kolkata', code: 'IN_KO' },
	{ name: 'India - Mumbai', code: 'IN_MB' },
	{ name: 'India - New Delhi', code: 'IN_ND' },
	{ name: 'Indonesia', code: 'ID' },
	{ name: 'Iran', code: 'IR' },
	{ name: 'Ireland', code: 'IE' },
	{ name: 'Iceland', code: 'IS' },
	{ name: 'Israel', code: 'IL' },
	{ name: 'Italy', code: 'IT' },
	{ name: 'Italy - Milan', code: 'IT_MI' },
	{ name: 'Italy - Rome', code: 'IT_RO' },
	{ name: 'Jamaica', code: 'JM' },
	{ name: 'Japan', code: 'JP' },
	{ name: 'Japan - Tokyo', code: 'JP_TK' },
	{ name: 'Jordan', code: 'JO' },
	{ name: 'Kazakhstan', code: 'KZ' },
	{ name: 'Kenya', code: 'KE' },
	{ name: 'Korea, Democratic People\'s Republic (North Korea)', code: 'KP' },
	{ name: 'Korea, Republic (South Korea)', code: 'KR' },
	{ name: 'Kosovo', code: 'XK' },
	{ name: 'Kuwait', code: 'KW' },
	{ name: 'Kyrgyztan', code: 'KG' },
	{ name: 'Laos', code: 'LA' },
	{ name: 'Latvia', code: 'LV' },
	{ name: 'Lebanon', code: 'LB' },
	{ name: 'Lesotho', code: 'LS' },
	{ name: 'Libya', code: 'LY' },
	{ name: 'Liechtenstein', code: 'LI' },
	{ name: 'Lithuania', code: 'LT' },
	{ name: 'Luxembourg', code: 'LU' },
	{ name: 'North Macedonia', code: 'MK' },
	{ name: 'Madagascar', code: 'MG' },
	{ name: 'Malawi', code: 'MW' },
	{ name: 'Malaysia', code: 'MY' },
	{ name: 'Maldives', code: 'MV' },
	{ name: 'Mali', code: 'ML' },
	{ name: 'Malta', code: 'MT' },
	{ name: 'Marshall Islands', code: 'MH' },
	{ name: 'Mauritania', code: 'MR' },
	{ name: 'Mauritius', code: 'MU' },
	{ name: 'Mexico', code: 'MX' },
	{ name: 'Micronesia', code: 'FM' },
	{ name: 'Moldova, Republic', code: 'MD' },
	{ name: 'Monaco', code: 'MC' },
	{ name: 'Mongolia', code: 'MN' },
	{ name: 'Montenegro', code: 'ME' },
	{ name: 'Morocco', code: 'MA' },
	{ name: 'Mozambique', code: 'MZ' },
	{ name: 'Myanmar', code: 'MM' },
	{ name: 'Namibia', code: 'NA' },
	{ name: 'Nepal', code: 'NP' },
	{ name: 'Netherland', code: 'NL' },
	{ name: 'New Zealand', code: 'NZ' },
	{ name: 'Nicaragua', code: 'NI' },
	{ name: 'Niger', code: 'NE' },
	{ name: 'Nigeria', code: 'NG' },
	{ name: 'Norway', code: 'NO' },
	{ name: 'Oman', code: 'OM' },
	{ name: 'Pakistan', code: 'PK' },
	{ name: 'Pakistan - Islamabad', code: 'PK_IS' },
	{ name: 'Palau', code: 'PW' },
	{ name: 'Panama', code: 'PA' },
	{ name: 'Papua New Guinea', code: 'PG' },
	{ name: 'Paraguay', code: 'PY' },
	{ name: 'Peru', code: 'PE' },
	{ name: 'Philippines', code: 'PH' },
	{ name: 'Poland', code: 'PL' },
	{ name: 'Poland - Breslau', code: 'PL_BR' },
	{ name: 'Poland - Gdańsk/Danzig', code: 'PL_GD' },
	{ name: 'Poland - Kraków/Krakau', code: 'PL_KR' },
	{ name: 'Poland - Warsaw/Warschau', code: 'PL_WA' },
	{ name: 'Portugal', code: 'PT' },
	{ name: 'Qatar', code: 'QA' },
	{ name: 'Romania', code: 'RO' },
	{ name: 'Romania - Bucharest', code: 'RO_BU' },
	{ name: 'Russian Federation', code: 'RU' },
	{ name: 'Russian Federation - Moscow', code: 'RU_MO' },
	{ name: 'Russian Federation - St. Petersburg', code: 'RU_SP' },
	{ name: 'Russian Federation - Yekaterinburg', code: 'RU_YK' },
	{ name: 'Rwanda', code: 'RW' },
	{ name: 'Samoa', code: 'WS' },
	{ name: 'San Marino', code: 'SM' },
	{ name: 'Sao Tome and Principe', code: 'ST' },
	{ name: 'Saudi Arabia', code: 'SA' },
	{ name: 'Saudi Arabia - Jeddah', code: 'SA_JD' },
	{ name: 'Saudi Arabia - Riyadh', code: 'SA_RD' },
	{ name: 'Senegal', code: 'SN' },
	{ name: 'Serbia', code: 'RS' },
	{ name: 'Sierra Leone', code: 'SL' },
	{ name: 'Singapore', code: 'SG' },
	{ name: 'Slovakia', code: 'SK' },
	{ name: 'Slovenia', code: 'SI' },
	{ name: 'Spain', code: 'ES' },
	{ name: 'Spain - Barcelona', code: 'ES_BC' },
	{ name: 'Spain - Canary Islands', code: 'ES_CA' },
	{ name: 'Spain - Madrid', code: 'ES_MA' },
	{ name: 'Spain - Palma de Mallorca', code: 'ES_PM' },
	{ name: 'South Africa', code: 'ZA' },
	{ name: 'South Africa - Cape Town', code: 'ZA_CT' },
	{ name: 'South Africa - Johannesburg', code: 'ZA_JH' },
	{ name: 'South Sudan', code: 'SS' },
	{ name: 'Sri Lanka', code: 'LK' },
	{ name: 'St. Kitts and Nevis', code: 'KN' },
	{ name: 'St. Lucia', code: 'LC' },
	{ name: 'St. Vincent and the Grenadines', code: 'VC' },
	{ name: 'Sudan', code: 'SD' },
	{ name: 'Suriname', code: 'SR' },
	{ name: 'Sweden', code: 'SE' },
	{ name: 'Switzerland', code: 'CH' },
	{ name: 'Switzerland - Geneva', code: 'CH_GE' },
	{ name: 'Syria', code: 'SY' },
	{ name: 'Taiwan', code: 'TW' },
	{ name: 'Tajikistan', code: 'TJ' },
	{ name: 'Tanzania', code: 'TZ' },
	{ name: 'Thailand', code: 'TH' },
	{ name: 'Togo', code: 'TG' },
	{ name: 'Tonga', code: 'TO' },
	{ name: 'Trinidad and Tobago', code: 'TT' },
	{ name: 'Tunisia', code: 'TN' },
	{ name: 'Turkey', code: 'TR' },
	{ name: 'Turkey - Istanbul', code: 'TR_IS' },
	{ name: 'Turkey - Izmir', code: 'TR_IZ' },
	{ name: 'Turkmenistan', code: 'TM' },
	{ name: 'Uganda', code: 'UG' },
	{ name: 'Ukraine', code: 'UA' },
	{ name: 'United Arab Emirates', code: 'AE' },
	{ name: 'United Kingdom', code: 'GB' },
	{ name: 'United Kingdom - London', code: 'GB_L' },
	{ name: 'United States', code: 'US' },
	{ name: 'United States - Atlanta', code: 'US_AT' },
	{ name: 'United States - Boston', code: 'US_BS' },
	{ name: 'United States - Chicago', code: 'US_CH' },
	{ name: 'United States - Houston', code: 'US_HU' },
	{ name: 'United States - Los Angeles', code: 'US_LA' },
	{ name: 'United States - Miami', code: 'US_MI' },
	{ name: 'United States - New York City', code: 'US_NYC' },
	{ name: 'United States - San Francisco', code: 'US_SF' },
	{ name: 'United States - Washington, D.C.', code: 'US_WDC' },
	{ name: 'Uruguay', code: 'UY' },
	{ name: 'Uzbekistan', code: 'UZ' },
	{ name: 'Vatican City', code: 'VA' },
	{ name: 'Venezuela', code: 'VE' },
	{ name: 'Vietnam', code: 'VN' },
	{ name: 'Yemen', code: 'YE' },
	{ name: 'Zambia', code: 'ZM' },
	{ name: 'Zimbabwe', code: 'ZW' },
] as const;
